Repository needpc/micro-api, pull requests merged in 2018-08, with the labels that each got.

#4 Adding index.html (apis docs)
  docs/apis/index.html
Labels: docs

#5 Docs/readme
  README.md
  dev-docker-compose.yml
Labels: docs

#6 Feature/prometheus
  README.md
  micro-services/get-activities/index.js
  micro-services/get-activities/package-lock.json
  micro-services/get-activities/package.json
  micro-services/get-ask/index.js
  micro-services/get-ask/package-lock.json
  micro-services/get-ask/package.json
  micro-services/get-brands/index.js
  micro-services/get-brands/package-lock.json
  micro-services/get-brands/package.json
  micro-services/get-computers-id/index.js
  micro-services/get-computers-id/package-lock.json
  micro-services/get-computers-id/package.json
  micro-services/get-computers/index.js
  micro-services/get-computers/package-lock.json
  micro-services/get-computers/package.json
  micro-services/get-cpus/index.js
  micro-services/get-cpus/package-lock.json
  micro-services/get-cpus/package.json
  micro-services/get-gpus/index.js
  micro-services/get-gpus/package-lock.json
  micro-services/get-gpus/package.json
Labels: docs, enhancement

#7 Apply values
  config/kubernetes-helm/configs/ark-values.yaml
  config/kubernetes-helm/configs/nginx-ingress-values.yaml
  config/kubernetes-helm/configs/prometheus-operator-values.yaml
  config/kubernetes-helm/configs/prometheus-values.yaml
  config/kubernetes-helm/cronjob.yaml
  config/kubernetes-helm/namespaces.yaml
Labels: enhancement

#11 HAProxy configuration
  config/haproxy/README.md
  config/haproxy/haproxy.cfg
  config/haproxy/install.sh
Labels: enhancement
